### 1) enter - 토큰 발급
POST http://127.0.0.1:8080/api/queue/enter
Content-Type: application/json

{
  "scheduleId": 1,
  "userId": 1001
}

> {%
    client.global.set("token", response.body.token);
    client.global.set("userId", "1001");
    client.global.set("scheduleId", "1");
%}

### 2) hold - 저장된 token 사용
POST http://127.0.0.1:8080/api/tickets/hold
Content-Type: application/json
X-QUEUE-TOKEN: {{token}}

{
  "scheduleId": {{scheduleId}},
  "seatNo": "A1",
  "userId": {{userId}}
}
